#!/bin/bash

while  true
do

RED='\033[0;31m'
GREEN='\033[1;32m'
NC='\033[0m'

echo "\nВставьте ключ АУ и сетевой кабель, если наберите OK для настройки или ничего для сброса скрипта"

read START

if [ "$START" == "ОК " ] || [ "$START" == "OK" ]
	then
		clear

		echo "\nВыключение виртуальной машины"

		VMs=$(xe vm-list is-control-domain=false params=uuid --minimal | sed 's/,/ /g')
		for uuid in $VMs
			do xe vm-shutdown uuid=$uuid
			done

		echo `printf "${GREEN}Done${NC}"`

		echo "\nДобавление ключа в виртуальную машину"

		USBkey=`xe pusb-list vendor-desc=Aktiv params=uuid --minimal | sed 's/,/ /g'`
		USBgroup=`xe pusb-list vendor-desc=Aktiv params=usb-group-uuid --minimal | sed 's/,/ /g'`
		xe pusb-param-set uuid=$USBkey passthrough-enabled=true
		xe vusb-create usb-group-uuid=$USBgroup vm-uuid=$uuid

		echo `printf "${GREEN}Done${NC}"`

		echo "\nПодключение LAN-портов напрямую в виртуальную машину"

		RESULT1=$(lspci -mm | grep Ethernet | cut -c1-7 | sed 's/^/0000:/g' )
		RESULT2=$(ethtool -i `ip addr | grep eth | grep "state UP" | cut -c4-7` | grep bus | cut -c11-22)
		for var in $RESULT1
			do
				if [ $var != $RESULT2 ]
					then
					echo $var >> tmp
					else
					echo "" |  sed '/^$/d'
				fi
			done
		PCIhide=`cat tmp | sed 's/^/(/' | tr -s '\n' ')'`
		/opt/xensource/libexec/xen-cmdline --set-dom0 "xen-pciback.hide=$PCIhide"
		PCIuuids=`cat tmp | sed 's/^/0\//' | tr -s '\n' ','| sed 's/.$//'`
		xe vm-param-set other-config:pci=$PCIuuids uuid=$uuid

		echo `printf "${GREEN}Done${NC}"`

		echo "\nАвтостарт виртуальной машины"

		xe vm-param-set uuid=$uuid other-config:auto_poweron=true

		echo `printf "${GREEN}Done${NC}"`
		echo "\nТеперь необходимо перезагрузить сервер для вступления изменений в работу"

		unset RESULT RESULT1 RESULT2 RESULT3 PCIhide PCIuuids uuid USBkey VMs
		break
	else
		echo "\nОтмена операции"
		break
fi
done
