#!/bin/bash

while  true
do

RED='\033[0;31m'
GREEN='\033[1;32m'
NC='\033[0m'
printf "\n"
echo "Insert AU key and network cable. Then type OK to configure or nothing to reset script"
printf "\n"
read START

if [ "$START" == "ОК " ] || [ "$START" == "OK" ]
	then
		clear
		printf "\n"
		echo "Shutting down of VM"
		printf "\n"
		VMs=$(xe vm-list is-control-domain=false params=uuid --minimal | sed 's/,/ /g')
		for uuid in $VMs
			do xe vm-shutdown uuid=$uuid
			done
		printf "\n"
		echo `printf "${GREEN}Done${NC}"`
		printf "\n"
		echo "Adding AU key to the system"
		printf "\n"
		USBkey=`xe pusb-list vendor-desc=Aktiv params=uuid --minimal | sed 's/,/ /g'`
		USBgroup=`xe pusb-list vendor-desc=Aktiv params=usb-group-uuid --minimal | sed 's/,/ /g'`
		xe pusb-param-set uuid=$USBkey passthrough-enabled=true
		xe vusb-create usb-group-uuid=$USBgroup vm-uuid=$uuid
		cp -rf usb_reset.py /opt/xensource/libexec/usb_reset.py
		printf "\n"
		echo `printf "${GREEN}Done${NC}"`
		printf "\n"
		echo "Connecting LAN-ports to the system"
		printf "\n"
		RESULT1=$(lspci -mm | grep Ethernet | cut -c1-7 | sed 's/^/0000:/g' )
		RESULT2=$(ethtool -i `ip addr | grep eth | grep "state UP" | cut -c4-7` | grep bus | cut -c11-22)
		for var in $RESULT1
			do
				if [ $var != $RESULT2 ]
					then
					echo $var >> tmp
					else
					echo "" |  sed '/^$/d'
				fi
			done
		PCIhide=`cat tmp | sed 's/^/(/' | tr -s '\n' ')'`
		/opt/xensource/libexec/xen-cmdline --set-dom0 "xen-pciback.hide=$PCIhide"
		PCIuuids=`cat tmp | sed 's/^/0\//' | tr -s '\n' ','| sed 's/.$//'`
		xe vm-param-set other-config:pci=$PCIuuids uuid=$uuid
		printf "\n"
		echo `printf "${GREEN}Done${NC}"`
		printf "\n"
		echo "Auto poweron to the VM"
		printf "\n"
		xe vm-param-set uuid=$uuid other-config:auto_poweron=true
		printf "\n"
		echo `printf "${GREEN}Done${NC}"`
		printf "\n"
		echo "Now you need to reboot the server"
		printf "\n"
		unset RESULT RESULT1 RESULT2 RESULT3 PCIhide PCIuuids uuid USBkey VMs
		rm -f tmp
		sleep 3
		break
	else
		clear
		printf "\n"
		echo "Cancel"
		printf "\n"
		break
fi
done
